# server:
#   port: 8080
# logging:
#   level:
#     root: INFO
#     org.springframework.web.reactive.function.client: DEBUG

# management:
#   endpoints:
#     web:
#       exposure:
#         include: health,info
